### ISSUE TITLE
Feature Request: Extend Practice Length

### ISSUE THREAD

**Issue by casithepython** [HumanoidSandvichDispenser/clear-your-desks#14]
Hi,

Just wondering whether it'd be possible to have the number of questions in a given practice run configurable in the GUI? Thanks.

**Comment by HumanoidSandvichDispenser** [comment]
![image](https://user-images.githubusercontent.com/25856867/230990466-836838f5-7be6-4fe4-9792-c867da3ff60c.png)

put something together and made the number of questions and average time per question configurable (10 questions + 120 seconds total by default)

**Comment by casithepython** [comment]
Thanks so much man! Really appreciated.
