### ISSUE TITLE
Better name

### ISSUE THREAD

**Issue by HumanoidSandvichDispenser** [HumanoidSandvichDispenser/clear-your-desks#2]
Better name for this project other than "Memory Quiz 2"

CC @minusArko

**Comment by HumanoidSandvichDispenser** [comment]
text-davinci-003 generated responses

List ideas for names of a calculus memory quiz practice game

1. Calculus Caliber
2. Calculus Memory Master
3. Math Memory Mania
4. Calculus Recall
5. Memory Marathon
6. Mental Math Magic
7. Calculus Challenge
8. Fun with Functions
9. Derivative Dash
10. Integral Insanity

**Comment by minusArko** [comment]
CalcMastery
    Calculus Flashcard Frenzy
    Integral Sprint
    Differential Dash
    Limit Lift-Off
    Function Frenzy
    Derivative Drilldown
    The Calculus Challenge
    The Ultimate Integral Invitational
    Differential Sprint: The Calculus Race
    Limit Leap: A Calculus Adventure
    The Calculus Conquest

**Comment by InspectorSchultz** [comment]
Calco Smalco
Smalco Caco
Calculi Universitatis 
Calcu the II
Dementor Of Calco
Demented Mathematics
Nerd Overload II
MQ2
Remember the Calculus . . .
In Memory of Calc.

**Comment by HumanoidSandvichDispenser** [comment]
@InspectorSchultz no one asked for your opinion :DDD

**Comment by HumanoidSandvichDispenser** [comment]
ur mom math = umm.sandvich.xyz

**Comment by HumanoidSandvichDispenser** [comment]
quiz ur memory = qum.sandvich.xyz
![](https://cdn.frankerfacez.com/emoticon/681239/1)

**Comment by HumanoidSandvichDispenser** [comment]
clear your desks
except for a pencil
